experimental_monorepo_root = true

[settings]
task_timings = false

[tools]
node = "22.21.1"
pulumi = "3.215.0"

[env]
MISE_EXPERIMENTAL = "true"

[monorepo]
config_roots = [
    "management/cloudflare",
    "management/truenas",
    "management/portainer",
]
