---
version: "3.9"

services:
  pocket-id:
    container_name: pocket-id
    # Use distroless image
    image: ghcr.io/pocket-id/pocket-id:v2.1.0-distroless
    restart: unless-stopped
    networks:
      home-bridge:
      cfd-bridge:
    volumes:
      - "$BUILTIN__APP_DATA_HOST_PATH/pocket-id:/app/data:rw"
    # Read only filesystem inside the container
    read_only: true
    # Run as non-root user
    user: "1002:3004"
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    environment:
      - APP_URL=https://auth.$BUILTIN__BASE_DOMAIN
      - ENCRYPTION_KEY=$GEN_BASE64_32__ENCRYPTION_KEY
      - TRUST_PROXY=true
      - MAXMIND_LICENSE_KEY=$SECRET__MAXMIND_LICENSE_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=home-bridge"
      - "traefik.http.routers.pocket-id.rule=Host(`auth.$BUILTIN__BASE_DOMAIN`)"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=1411"
networks:
  home-bridge:
    external: true
  cfd-bridge:
    external: true
