name: Stack Preview (Pulumi)
on:
  workflow_call:
    inputs:
      project-name:
        description: "Name of the project to work in"
        required: true
        type: string
      project-parent-path:
        description: "Path of the parent directory containing the project"
        required: false
        type: string
        default: "."
      stack-name:
        description: "Name of the stack to preview"
        required: true
        type: string
      pulumi-org:
        description: "Personal pulumi organization name"
        required: false
        type: string
        default: "gunzy83"

permissions:
  contents: read # required for checkout
  id-token: write # required to request id-token for OIDC authentication

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: "${{ inputs.project-name }}-deploy"
      url: ${{ steps.pulumi_up.outputs.cloud-url }}
    env:
      working-directory: ${{ inputs.project-parent-path }}/${{ inputs.project-name }}
      MISE_ENV: "ci"
      # requires secrets: inherit in calling workflow
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_AUDIENCE: ${{ secrets.TS_AUDIENCE }}
    steps:
      - name: âœ… Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ› ï¸ Setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
        with:
          experimental: true # required for monorepo support
          working_directory: ${{ env.working-directory }}

      - name: ğŸ› ï¸ Configuration checks
        id: config_checks
        run: |
          # load mise environment
          eval "$(mise env -s bash)"
          # get pulumi version
          # https://github.com/pulumi/actions/issues/638
          echo "pulumi_version=$(mise tool pulumi --active)" > "$GITHUB_OUTPUT"
          # read JOIN_TAILNET env var
          echo "join_tailnet=$JOIN_TAILNET" >> "$GITHUB_OUTPUT"
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: ğŸ› ï¸ Install node dependencies
        run: |
          npm ci
        working-directory: ${{ env.working-directory }}

      - name: ğŸ› ï¸ Install plugins/terraform providers
        run: |
          pulumi install --no-dependencies
        working-directory: ${{ env.working-directory }}

      - name: ğŸ” Authenticate pulumi cloud
        uses: pulumi/auth-actions@1c89817aab0c66407723cdef72b05266e7376640 # v1
        with:
          organization: ${{ inputs.pulumi-org }}
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:${{ inputs.pulumi-org }}

      - name: ğŸ” Connect to tailnet
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4
        if: ${{ steps.config_checks.outputs.join_tailnet == 'true' }}
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          audience: ${{ env.TS_AUDIENCE }}
          tags: "tag:github-actions-${{ inputs.project-name }}"
          hostname: "github-actions-runner-${{ inputs.project-name }}"

      - name: ğŸš€ Run pulumi up
        uses: gunzy83/pulumi-actions@03d7f0a5d03335352bcaaaabeb51535058104c0a # v6
        id: pulumi_up
        with:
          command: up
          stack-name: ${{ inputs.pulumi-org }}/${{ inputs.stack-name }}
          pulumi-version: ${{ steps.config_checks.outputs.pulumi_version }}
          work-dir: ${{ env.working-directory }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          comment-on-summary: true
